title: quantum Ratio
logo: /assets/images/logo.png
description: Solutions through custom APIs and cutting edge technology. Fostering community and advancment through open source commitment.
url: www.quantumratio.com

theme: jekyll-theme-minimal
