title: quantumRatio
logo: LogoMakr_9mDuRK.png
description: Stealth Mode #Solutions through custom APIs and cutting edge technology. Fostering community and advancment through open source commitment.
url: https://quantumratio.github.io/

theme: jekyll-theme-minimal
