title: quantum Ratio
logo: 7ef03d80-78a1-4d57-9a72-fbd4c8353a39_200x200.png
description: Stealth Mode #Solutions through custom APIs and cutting edge technology. Fostering community and advancment through open source commitment.
url: https://quantumratio.github.io/

theme: jekyll-theme-minimal
